# Generated by Django 4.2.11 on 2024-06-14 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_cardss_coordinates_alter_cardss_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardss',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка'),
        ),
    ]
