# Generated by Django 4.2.11 on 2024-06-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_cardss_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardss',
            name='usersCount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество пользователей'),
        ),
    ]
