# Generated by Django 4.2.11 on 2024-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
