# Generated by Django 4.2.11 on 2024-05-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0005_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
