# Generated by Django 4.2.11 on 2024-06-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0006_remove_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
