# Generated by Django 4.2.11 on 2024-06-13 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0007_remove_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка'),
        ),
    ]
